# Generated by Django 4.1.2 on 2022-11-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject", models.CharField(max_length=120)),
            ],
            options={"db_table": "book",},
        ),
        migrations.CreateModel(
            name="Student_mat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject", models.CharField(max_length=120)),
                ("Attendens", models.CharField(max_length=120)),
                ("Assignment", models.CharField(max_length=120)),
                ("Marks", models.IntegerField(max_length=120)),
            ],
            options={"db_table": "student_mat",},
        ),
        migrations.CreateModel(
            name="Teacher_mat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Subject", models.CharField(max_length=120)),
                ("Complate_assignment", models.CharField(max_length=120)),
                ("Pendding_assigment", models.CharField(max_length=120)),
                ("Exam", models.IntegerField(max_length=120)),
            ],
            options={"db_table": "teacher_mat",},
        ),
    ]
