# Generated by Django 4.1.1 on 2022-11-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0002_book_student_mat_teacher_mat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher", old_name="compensation", new_name="Subject",
        ),
    ]
