# Generated by Django 4.1.1 on 2022-11-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0003_rename_compensation_teacher_subject"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="Subject",),
    ]
