# Generated by Django 4.1.1 on 2022-11-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0004_remove_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="Isactive",
            field=models.BooleanField(default=True),
        ),
    ]
