# Generated by Django 4.1.1 on 2022-11-16 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0006_alter_master_isactive"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacherr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "Master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituteapp.master",
                    ),
                ),
            ],
            options={"db_table": "teacherr",},
        ),
    ]
