# Generated by Django 4.1.1 on 2022-11-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instituteapp", "0007_teacherr"),
    ]

    operations = [
        migrations.AlterModelTable(name="userrole", table="userrole",),
    ]
